"""
app.py – FastAPI web server + REST API
"""
import os
import logging
import contextlib
import json
import re
from fastapi import FastAPI, Request, HTTPException, Query
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
)
logger = logging.getLogger(__name__)

# ── App lifecycle ──────────────────────────────────────────────────────────────
import database as db
import scheduler as sched


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Bootstrapping database…")
    db.bootstrap_schema()
    logger.info("Starting background scheduler…")
    sched.start_scheduler()
    yield
    sched.stop_scheduler()


app = FastAPI(
    title="MindPulse",
    description="AI-powered knowledge blog featuring curated articles on Technology, Science, Business, Health, and Society — generated by Groq LLM",
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url=None,
)

templates = Jinja2Templates(directory="templates")

# Mount static files if the directory exists
static_path = os.path.join(os.path.dirname(__file__), "static")
if os.path.isdir(static_path):
    app.mount("/static", StaticFiles(directory=static_path), name="static")


def parse_insight(item: dict) -> dict:
    # Use summary field as raw since that's where the JSON is stored
    raw = item.get('full_content', '')
    if not raw:
        return item

    summary_match = re.search(r'"summary"\s*:\s*"(.*?)"(?=\s*,\s*\n\s*")', raw, re.DOTALL)
    item['summary'] = summary_match.group(1).strip() if summary_match else raw

    content_match = re.search(r'"full_content"\s*:\s*"(.*?)"(?=\s*,\s*\n\s*"|\s*\n\s*})', raw, re.DOTALL)
    item['full_content'] = content_match.group(1).strip() if content_match else raw

    key_points_block = re.search(r'"key_points"\s*:\s*\[(.*?)\]', raw, re.DOTALL)
    if key_points_block:
        item['key_points'] = re.findall(r'"(.*?)"(?=\s*[,\]])', key_points_block.group(1), re.DOTALL)
    else:
        item['key_points'] = []

    return item

# ── HTML Dashboard / Blog Home ───────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    stats = db.fetch_stats()
    featured = [parse_insight(i) for i in db.fetch_insights(limit=1)]
    insights = [parse_insight(i) for i in db.fetch_insights(limit=10, offset=1)]
    next_run = sched.get_next_run()
    interval = int(os.getenv("POPULATE_INTERVAL_SECONDS", "300"))

    return templates.TemplateResponse("index.html", {
        "request": request,
        "stats": stats,
        "featured": featured,
        "insights": insights,
        "next_run": next_run,
        "interval": interval,
    })


@app.get("/insight/{insight_id}", response_class=HTMLResponse)
async def insight_detail(request: Request, insight_id: int):
    """Individual article page"""
    item = db.fetch_insight_detail(insight_id)
    if not item:
        raise HTTPException(status_code=404, detail="Article not found")
    
    if item.get('full_content'):
        raw = item['full_content']

        # Extract summary
        summary_match = re.search(r'"summary"\s*:\s*"(.*?)"(?=\s*,\s*")', raw, re.DOTALL)
        item['summary'] = summary_match.group(1).strip() if summary_match else item.get('summary', '')

        # Extract full_content (the long article text)
        content_match = re.search(r'"full_content"\s*:\s*"(.*?)"(?=\s*,\s*"\w|}\s*$)', raw, re.DOTALL)
        item['full_content'] = content_match.group(1).strip() if content_match else raw

        # Extract key_points as a list
        key_points_block = re.search(r'"key_points"\s*:\s*\[(.*?)\]', raw, re.DOTALL)
        if key_points_block:
            item['key_points'] = re.findall(r'"(.*?)"(?=\s*[,\]])', key_points_block.group(1), re.DOTALL)
        else:
            item['key_points'] = []

    return templates.TemplateResponse("detail.html", {
        "request": request,
        "item": item,
    })


@app.get("/insights", response_class=HTMLResponse)
async def insights_list(request: Request, category: str | None = None):
    """Browse all articles, optionally filtered by category"""
    cat_filter = category if category else None
    stats = db.fetch_stats()
    insights = db.fetch_insights(limit=20, category=cat_filter)
    return templates.TemplateResponse("index.html", {
        "request": request,
        "stats": stats,
        "featured": [],
        "insights": insights,
        "next_run": sched.get_next_run(),
        "interval": int(os.getenv("POPULATE_INTERVAL_SECONDS", "300")),
    })


@app.get("/latest", response_class=HTMLResponse)
async def latest_articles(request: Request):
    """Latest articles page"""
    stats = db.fetch_stats()
    insights = db.fetch_insights(limit=20)
    return templates.TemplateResponse("index.html", {
        "request": request,
        "stats": stats,
        "featured": [],
        "insights": insights,
        "next_run": sched.get_next_run(),
        "interval": int(os.getenv("POPULATE_INTERVAL_SECONDS", "300")),
    })


@app.get("/about", response_class=HTMLResponse)
async def about(request: Request):
    """About page"""
    stats = db.fetch_stats()
    return templates.TemplateResponse("about.html", {"request": request, "stats": stats})


# ── REST API ───────────────────────────────────────────────────────────────────

@app.get("/api/insights")
async def api_insights(
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
    category: str | None = Query(default=None),
):
    rows = db.fetch_insights(limit=limit, offset=offset, category=category)
    # Convert datetime objects to strings
    for r in rows:
        if r.get("created_at"):
            r["created_at"] = r["created_at"].isoformat()
    return {"data": rows, "count": len(rows)}


@app.get("/api/stats")
async def api_stats():
    stats = db.fetch_stats()
    # Serialise datetimes
    for run in stats.get("recent_runs", []):
        if run.get("run_at"):
            run["run_at"] = run["run_at"].isoformat()
    stats["next_run"] = sched.get_next_run()
    stats["interval_seconds"] = int(os.getenv("POPULATE_INTERVAL_SECONDS", "300"))
    return stats


@app.get("/api/logs")
async def api_logs(limit: int = Query(default=50, ge=1, le=500)):
    logs = db.fetch_logs(limit=limit)
    for log in logs:
        if log.get("created_at"):
            log["created_at"] = log["created_at"].isoformat()
    return {"data": logs}


class IntervalRequest(BaseModel):
    seconds: int


@app.post("/api/scheduler/interval")
async def set_interval(body: IntervalRequest):
    if body.seconds < 30:
        raise HTTPException(status_code=400, detail="Interval must be ≥ 30 seconds")
    sched.update_interval(body.seconds)
    return {"message": f"Interval updated to {body.seconds}s"}


@app.post("/api/scheduler/run-now")
async def run_now():
    """Trigger an immediate population run (async via scheduler)."""
    import threading
    t = threading.Thread(target=sched.populate_database, daemon=True)
    t.start()
    return {"message": "Population run triggered"}


@app.get("/api/insight/{insight_id}")
async def api_insight_detail(insight_id: int):
    item = db.fetch_insight_detail(insight_id)
    if not item:
        raise HTTPException(status_code=404, detail="Not found")
    if item.get("created_at"):
        item["created_at"] = item["created_at"].isoformat()
    if item.get('full_content'):
        raw = item['full_content']
        
        # Extract summary
        summary_match = re.search(r'"summary"\s*:\s*"(.*?)"(?=\s*,\s*")', raw, re.DOTALL)
        item['summary'] = summary_match.group(1).strip() if summary_match else item.get('summary', '')
        
        # Extract full_content (the long article text)
        content_match = re.search(r'"full_content"\s*:\s*"(.*?)"(?=\s*,\s*"\w|}\s*$)', raw, re.DOTALL)
        item['full_content'] = content_match.group(1).strip() if content_match else raw
        
        # Extract key_points as a list
        key_points_block = re.search(r'"key_points"\s*:\s*\[(.*?)\]', raw, re.DOTALL)
        if key_points_block:
            item['key_points'] = re.findall(r'"(.*?)"(?=\s*[,\]])', key_points_block.group(1), re.DOTALL)
        else:
            item['key_points'] = []
    return item


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("app:app", host="0.0.0.0", port=port, reload=False)
